index.html
htmlacademy-htmlcss/2515835-sedona-1 pull request #2
Opened 2024-05-14 15:40 UTC by Tuvakova

2024-05-14 17:24 UTC, NikolaiKotikov requested changes
В общем хорошо, но нужно еще сверстать `catalog.html`

2024-05-14 17:24 UTC, NikolaiKotikov commented on index.html
> +            <h3 class="advantages-title">Настоящий городок</h3>
h3 идет сразу после h1, а где h2?

2024-05-14 17:24 UTC, NikolaiKotikov commented on index.html
> +      <h2>+7 (812) 812-12-12 </h2>
Телефон лучше сделать ссылкой, а не заголовком

2024-05-15 08:48 UTC, Tuvakova commented on index.html
> +            <h3 class="advantages-title">Настоящий городок</h3>
Я добавила h2 и ссылку сделала.Осталось только каталог.

2024-05-20 13:36 UTC, NikolaiKotikov requested changes

2024-05-20 13:36 UTC, NikolaiKotikov commented on catalog.html
> +    </div>
Все элементы форм должны находиться в теге `form`. У инпутов должен быть атрибут "id"

2024-05-20 13:36 UTC, NikolaiKotikov commented on catalog.html
> +      <a class="button button-all" href="#">Сбросить</a>
Это должы быть кнопки. 
"Применить" - button type submit
"Сбросить" - button type reset

2024-05-20 13:36 UTC, NikolaiKotikov commented on catalog.html
> +            <label for="simple-rating-1" class="simple-rating-label"></label>
тут нужно просто показать рейтинг, изменение прямо из карточки не предусмотрено, поэтому инпуты излишни

2024-05-20 13:36 UTC, NikolaiKotikov commented on catalog.html
> +            <a class="button button-all" href="#">Подписаться</a>
здесь тоже button type submit

2024-05-20 13:36 UTC, NikolaiKotikov commented on catalog.html
> +      <h3>.html academy </h3>
Это логотип, поэтому лучше сделать его в свг потом, но пока можно оставить так

2024-05-20 13:36 UTC, NikolaiKotikov commented on catalog.html
> +          <a class="navigation-link navigation-link-current" href="#">Главная</a>
класс navigation-link-current нужно повесть на ссылку "Гостиницы", мы же на этой странице находимся

2024-05-21 10:01 UTC, merged