images
htmlacademy-htmlcss/2515835-sedona-1 pull request #3
Opened 2024-05-25 14:05 UTC by Tuvakova

2024-05-25 18:28 UTC, NikolaiKotikov requested changes
Файлы и папки должны быть записаны строчными буквами без пробелов между словами, критерий [PROJ-03.](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-03). Проверь все. Неправильно например Sedona.svg (С большой буквы) и есть еще другие. В общем, советую ознакомиться со всеми критериями и сверяться с ними время от времени

2024-05-25 18:28 UTC, NikolaiKotikov commented on catalog.html
> +            <img src="images/favourites.svg" alt=" Избранное" width="44" height="70">
Изображением должна быть только иконка, счетчик нужно сверстать. Это нужно для того, чтобы потом была возможность менять счетчик программно.

2024-05-25 18:28 UTC, NikolaiKotikov commented on index.html
> +          <img src="images/vk.svg" alt="ВКонтакте" width="47.33" height="40">
Дробных значений лучше избегать, округляй до целого

2024-05-25 18:28 UTC, NikolaiKotikov commented on catalog.html
> +        <img class="page-header-logo" alt="Логотип городка Седона." width="140" height="70">
где src?

2024-05-25 20:24 UTC, Tuvakova commented on catalog.html
> +            <img src="images/favourites.svg" alt=" Избранное" width="44" height="70">
Какой счетчик? я не поняла

2024-05-26 09:58 UTC, NikolaiKotikov commented on catalog.html
> +            <img src="images/favourites.svg" alt=" Избранное" width="44" height="70">
Цифра в круге

2024-05-26 19:33 UTC, NikolaiKotikov requested changes

2024-05-26 19:33 UTC, NikolaiKotikov commented on catalog.html
> +            <span>12</span>
Мало просто добавить спан. Нужно еще изменить само изображение, оставить только иконку без счетчика

2024-05-26 19:33 UTC, NikolaiKotikov commented on index.html
> +      <img src="images/Vector (2) (1).svg" alt="подпись" width="256" height="29">
Я писал о том, что нужно изменить наименования файлов, чтобы соответствовать критериям, это все еще нужно сделать

2024-05-27 10:26 UTC, merged